#!/usr/bin/env python3
"""Turn the cleaned sink photos into a gallery data file.

One entry per vanity. Where the owner sent more than one angle of the same unit (same
stone colour + sink count + basin type) the photos are grouped under one entry so the
page shows a gallery instead of scattered near-duplicates. Every published photo must
appear exactly once — assert that, since a filter bug here silently drops images.
"""
import json, collections

BATCH = "/opt/data/cache/scratch/sinkbatch"
OUT = "/opt/data/projects/diarna-stone/src/data/sink-gallery.js"

AR = {"single": "مفردة", "double": "مزدوجة", "triple": "ثلاثية", "quad": "رباعية"}
BASIN = {"undermount": "مدمجة Undermount", "vessel": "علوية Vessel",
         "integrated": "مدمجة بالكامل"}
SETTING = {"installed": "مركّبة في حمام", "showroom": "من معرض العرض",
           "under_construction": "قيد التركيب", "workshop": "من الورشة"}
STONE = {"marble": "رخام", "granite": "جرانيت", "travertine": "ترا فرتينو",
         "limestone": "حجر جيري", "ceramic": "سيراميك"}


def label(e):
    parts = [AR.get(e["type"], e["type"]), BASIN.get(e["basin"], e["basin"])]
    return " · ".join(p for p in parts if p)


def main():
    m = json.load(open(f"{BATCH}/publish_manifest.json", encoding="utf-8"))
    pub = m["published"]

    groups = collections.defaultdict(list)
    for p in pub:
        key = "|".join([p.get("stone_color", ""), p.get("type", ""),
                        p.get("basin", ""), p.get("counter", "")])
        groups[key].append(p)

    entries = []
    for i, (key, members) in enumerate(
            sorted(groups.items(), key=lambda kv: (-len(kv[1]), kv[0])), start=1):
        rep = members[0]
        entries.append({
            "slug": f"s{i:02d}",
            "name": rep["stone_color"],
            "stoneType": rep.get("stone_type", ""),
            "type": rep.get("type", ""),
            "basin": rep.get("basin", ""),
            "setting": rep.get("setting", ""),
            "photos": [x["out"] for x in members],
            "altEn": members[0].get("alt_en", ""),
            "count": len(members),
            "description_ar": " · ".join(filter(None, [
                STONE.get(rep.get("stone_type", ""), ""),
                label(rep),
                SETTING.get(rep.get("setting", ""), ""),
            ])),
        })

    # integrity: every published photo appears exactly once
    flat = [p for e in entries for p in e["photos"]]
    assert len(flat) == len(pub), f"photo count mismatch: {len(flat)} vs {len(pub)}"
    assert len(set(flat)) == len(flat), "a photo appears in more than one entry"
    missing = {p["out"] for p in pub} - set(flat)
    assert not missing, f"photos dropped: {sorted(missing)}"

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by src/data/build-gallery.py from the owner's sink photos.\n")
        f.write("// One entry per vanity; multi-photo entries hold several angles of the\n")
        f.write("// same unit, so the page shows a gallery rather than near-duplicates.\n")
        f.write("export default " + json.dumps(entries, ensure_ascii=False, indent=1) + ";\n")

    multi = [e for e in entries if e["count"] > 1]
    print(f"entries        : {len(entries)}  ({len(multi)} with more than one photo)")
    print(f"photos covered : {len(flat)} / {len(pub)}  — every published photo accounted for")
    print(f"sink counts    : {dict(collections.Counter(e['type'] for e in entries))}")
    print(f"basins         : {dict(collections.Counter(e['basin'] for e in entries))}")
    for e in multi:
        print(f"   {e['slug']} x{e['count']}  {e['name']} — {e['description_ar']}")


if __name__ == "__main__":
    main()